FreeDiscovery/FreeDiscovery

.travis.yml, Makefile, README.rst, appveyor.yml, build_tools/conda_setup.sh, freediscovery/categorization.py, freediscovery/clustering/base.py, freediscovery/simhash/dupdet.py, freediscovery/tests/run_suite.py, freediscovery/tests/test_categorization.py
This PR fixes a minor issue with the Python 2 Travis CI build.
=> Fixing Python 2 build 

build_tools/circle/build_doc.sh, build_tools/circle/check_build_doc.py, build_tools/circle/push_doc.sh, circle.yml, examples/categorization_example.py, examples/clustering_example.py, examples/clustering_example_python.py
This fixes issue #3  by,
- automatically building the docs and uploading them to https://freediscovery.github.io/doc/dev/ when Pull Requests are merged into master (adapted from the scikit-learn CI setup). 
- adding examples to this repo, by putting them under `examples/` folder in the .py format.
=> FIX automatically build docs

examples/categorization_example.py, examples/clustering_example.py, examples/clustering_example_python.py, freediscovery/api/app.py, freediscovery/api/resources.py, freediscovery/api/schemas.py, freediscovery/base.py, freediscovery/categorization.py, freediscovery/clustering/__init__.py, freediscovery/clustering/base.py, freediscovery/clustering/dendogram.py, freediscovery/exceptions.py, freediscovery/lsi.py, freediscovery/simhash/base.py, freediscovery/simhash/dupdet.py, freediscovery/tests/run_suite.py, freediscovery/tests/test_api.py, freediscovery/tests/test_categorization.py, freediscovery/tests/test_clustering.py, freediscovery/tests/test_dupdetection.py, freediscovery/tests/test_io.py, freediscovery/tests/test_lsi.py, freediscovery/tests/test_text.py, freediscovery/text.py, freediscovery/utils.py
Various styles improvements for the release: PEP8, empty lines, unused imports
Thanks for this @DenisFLASH! Sorry, merging it now, as otherwise I'll get conflicts with my other changes.
=> Style improvements

doc/deployment.md, doc/index.rst, doc/scaling_benchmarks.rst, docker_run.sh, examples/duplicate_detection_example.py, freediscovery/_version.py, freediscovery/datasets.py, freediscovery/tests/test_dupdetect.py, freediscovery/tests/test_text.py
Various small fixes for the 0.6-beta release
=> Various updates for 0.6-beta

.travis.yml, build_tools/requirements_extra_pip.txt, build_tools/requirements_pip_unix.txt, build_tools/requirements_pip_win.txt, examples/categorization_example.py
This PR updates the scikit-learn version  used by default from 0.17.1 to 0.18.1 (issue #8) to take advantage of the latest improvements and bug fixes.
=> FIX Migrate to scikit-learn 0.18.1

doc/contributing.md, doc/installation_instructions.md, doc/python_api.rst, doc/rest_api/index.rst, doc/scaling_benchmarks.rst, examples/README.txt, examples/categorization_example.py, examples/clustering_example.py, examples/duplicate_detection_example.py, freediscovery/server/resources.py, freediscovery/tests/test_server.py, freediscovery/text.py
A few more improvements of the documentation and examples.
=> Docs / examples improvements

examples/categorization_example.py, examples/clustering_example.py, examples/duplicate_detection_example.py, freediscovery/tests/test_server.py, freediscovery/text.py
Fixes an issue in unit tests of the   `list_datasets`  endpoint and  and improves examples. Thanks @DenisFLASH .
=> FIX list datasets and imporve examples

.travis.yml, appveyor.yml, build_tools/conda_setup.sh, build_tools/requirements_conda.txt, build_tools/requirements_pip_unix.txt, build_tools/requirements_pip_win.txt
Minor maintenance changes,
- adds a conda-forge channel for installing FreeDiscovery (which would make cross-platform easier, #10)
- remove a few standard packages from the dependencies (issue #7 )
=> MNT: Improve dependencies handling

.travis.yml, appveyor.yml, build_tools/circle/build_doc.sh, build_tools/requirements_pip.txt, build_tools/requirements_pip_comp.txt, build_tools/requirements_pip_unix.txt, build_tools/requirements_pip_win.txt, doc/installation_instructions.md, examples/categorization_example_python.py, examples/duplicate_detection_example.py, examples/email_threading_example.py
In PR includes, 
- a fix for issue #39 for testing examples on Windows
- remove the xgboost dependency as it is not used by default anymore and can pose installation issues
- updated the docs with an explicit requirement for a C++ compiler (to install simhash-py on Linux)
=> Improved build scripts

doc/python_api.rst, freediscovery/base.py, freediscovery/categorization.py, freediscovery/cluster/base.py, freediscovery/dupdet/base.py, freediscovery/lsi.py, freediscovery/parsers.py, freediscovery/server/resources.py, freediscovery/tests/test_cluster.py, freediscovery/tests/test_integration.py, freediscovery/tests/test_lsi.py, freediscovery/text.py, freediscovery/threading.py, freediscovery/utils.py
This PR includes the following modifications,
- factorizes redundant  code in `__init__`, `_load_pars`, and `_load_model` from individual wrappers to the `_BaseWrapper` class
- changes the default uuid lenght in the REST API urls from 32 char (hex) to 16 char (for more readability), given the low chance of collision.
=> Factorization of wrapper methods

README.rst, doc/contributing.md, doc/installation_instructions.md
This adds a brief description of the possible workflow for adding pull request in the docs  (which can be later improved). It also fixes minor formatting issues in the Readme.
=> Adding contribution instructions

doc/rest_api/lsi_delete.md, doc/rest_api/lsi_get.md
Adding overview pages for show the Latent Semantic Indexing (LSI) model parameters and delete the Latent Semantic Indexing (LSI) model to the REST API Reference.
=> Added overview pages for LSI to the REST API Reference

doc/rest_api/lsi_get.md, freediscovery/tests/test_server.py
Added the expected response of GET `lsi/<lsi-id>` to `lsi_get.md` and additional `assert`s to the corresponding unit test.
=> Added the expected response of GET lsi/<lsi-id> and additional asserts

doc/rest_api/categorization_post.md, doc/rest_api/feature_extraction_post.md
Improve the docs for REST API data ingestion.
=> DOC: fix the missing desciption of an input parameter

freediscovery/server/resources.py, freediscovery/tests/test_server.py, freediscovery/utils.py
This PR fixes an issue in the REST API for unsupervised Nearest Neighbor categorization. 
Fix for `0.8.X` branch, will also be applied to `master`.
=> FIX: bug in categorization API for unsupervised NN

.travis.yml, Dockerfile, appveyor.yml, build_tools/circle/build_doc.sh, build_tools/conda_setup.bat, build_tools/conda_setup.sh, build_tools/requirements_conda.txt, build_tools/requirements_extra_pip.txt, build_tools/requirements_pip.txt, doc/installation_instructions.md, freediscovery/externals/__init__.py, freediscovery/externals/jwzthreading.py, freediscovery/parsers.py, freediscovery/tests/test_parsers.py, freediscovery/threading.py, requirements.txt
This PR simplifies the install process, bundles the jwzthreading package (therefore removing it as a dependency, issue #7 ), and upgrades to PY3.6 by default (which should result in some small performance improvements).
=> Improve packaging

build_tools/circle/build_doc.sh, doc/_templates/layout.html, doc/rest_api.rst, doc/whats_new.md, examples/REST_categorization.py, examples/REST_clustering.py, examples/REST_data_ingestion.py, examples/REST_duplicate_detection.py, examples/REST_email_threading.py, examples/REST_semantic_search.py, freediscovery/server/app.py, freediscovery/server/resources.py, freediscovery/server/schemas.py, freediscovery/tests/test_server.py
This PR,
- fixes a few formatting issues in the docs
- Changes some endpoints with a non empty requests body from GET->POST 
- Renamed the /datasets/ endpoint to /example-datasets/
=> FIX:  formatting and API request types

freediscovery/server/app.py, freediscovery/tests/test_server.py
This fixes issue #72 regarding unit tests of the REST API with nested dicts input.
=> FIX: Unit tests of the REST API with nested dicts input

doc/whats_new.md, examples/REST_categorization.py, examples/REST_data_ingestion.py, freediscovery/ingestion.py, freediscovery/search.py, freediscovery/server/app.py, freediscovery/server/resources.py, freediscovery/server/tests/base.py, freediscovery/server/tests/test_categorization.py, freediscovery/server/tests/test_ingestion.py, freediscovery/server/tests/test_search.py
This PR, removes somewhat redundant API endpoints for data ingestion / id mapping and adds additional unit tests.
=> Additional tests and REST API simplifications

doc/python_api.rst, doc/whats_new.md, examples/REST_categorization.py, freediscovery/metrics.py, freediscovery/server/resources.py, freediscovery/server/schemas.py, freediscovery/server/tests/test_categorization.py, freediscovery/tests/test_base.py, freediscovery/tests/test_categorize.py, freediscovery/tests/test_integration.py, freediscovery/tests/test_lsi.py, freediscovery/tests/test_metrics.py, freediscovery/utils.py
This PR fixes issue #30 and adds a recall at K score.
=> FIX Add a recall at K scores

freediscovery/server/resources.py, freediscovery/server/tests/test_search.py
This PR adds `sort` and `max_results` parameters to the Search API, in order to allow sorting of the results, and returning only first `max_results` items.
=> Added sort and max_results parameters to Search API

freediscovery/server/resources.py, freediscovery/server/schemas.py, freediscovery/server/tests/test_ingestion.py
=> fix bugs in feature-extraction REST API

freediscovery/server/resources.py, freediscovery/server/tests/base.py, freediscovery/server/tests/test_ingestion.py, freediscovery/stop_words.py, freediscovery/text.py
This PR integrates the existing mechanism for  adding / deleting custom stop words with the feature extraction module.
=> Custom stop words integration

freediscovery/categorization.py, freediscovery/server/resources.py, freediscovery/server/tests/test_categorization.py
This PR adds the parameter `subset` to the categorization prediction, which allows to predict scores either for all the documents in the collection or the training / test set only.
=> Subset selection for categorization

doc/installation_instructions.md, freediscovery/base.py, freediscovery/datasets.py, freediscovery/ingestion.py, freediscovery/lsi.py, freediscovery/server/app.py, freediscovery/server/resources.py, freediscovery/server/schemas.py, freediscovery/server/tests/test_ingestion.py, freediscovery/server/tests/test_search.py, freediscovery/tests/test_ingestion.py, freediscovery/tests/test_lsi.py, freediscovery/tests/test_text.py, freediscovery/text.py
=> FIX Ability to add / delete documents

freediscovery/__main__.py, freediscovery/categorization.py, freediscovery/ingestion.py, freediscovery/server/resources.py, freediscovery/server/tests/test_categorization.py, freediscovery/server/tests/test_search.py
This PR allows to categorize or search a subset of the document collection (specified by the `subset_document_id` list parameter)
=> Categorize / search a subset of the document collection

freediscovery/categorization.py, freediscovery/search.py, freediscovery/server/resources.py, freediscovery/server/schemas.py, freediscovery/server/tests/base.py, freediscovery/server/tests/test_ingestion.py, freediscovery/server/tests/test_search.py, freediscovery/text.py, requirements.txt
Add a few more tests (including some validation using Discounted Cumulative Gain score) for the semantic search.
=> Additional tests for semantic search

.travis.yml, freediscovery/lsi.py, freediscovery/server/resources.py, freediscovery/tests/test_lsi.py
This PR allows to automatically decrease the number of dimensions in LSA when ingesting small datasets.
=> Automatically reduce the number of dimensions in LSA

doc/python_api.rst, freediscovery/feature_weighting.py, freediscovery/search.py, freediscovery/tests/test_base.py, freediscovery/tests/test_feature_weighting.py, setup.py
Implementation of the term, documents weighting and normalization using the  [SMART notation](https://nlp.stanford.edu/IR-book/html/htmledition/document-and-query-weighting-schemes-1.html).  All the schemes are implemented, expect for the pivoted normalization that will be added in the following PR.
=> SMART feature weighting

build_tools/circle/install.sh, examples/fd_engine/hierarchical_clustering_visualization_example.py
This PR adds an example to http://freediscovery.io/doc/dev/engine/examples/ with a graphviz  visualization of hierarchical clusters obtained on a subset of the 20 newsgoups dataset,
=> Hierarchical clustering visualization example

freediscovery/feature_weighting.py, freediscovery/server/resources.py, freediscovery/server/schemas.py, freediscovery/server/tests/test_ingestion.py, freediscovery/tests/test_feature_weighting.py, freediscovery/text.py, freediscovery/utils.py, requirements.txt
This adds,
* cosine pivoted document length normalizations (`weighting="**p"` in SMART notation)
* pivoted unique document lenght normalization (`weighting="**u"` in SMART notation)
from [Singhal et al. 1996](http://singhal.info/pivoted-dln.pdf).
=> Pivoted document length normalizations

circle.yml, doc/user_manual/document_similarity.rst, freediscovery/ranking_adjustement.py, freediscovery/tests/test_ranking_adjustement.py
Better documentation for the document-term weighting schemes and a few (experimental) helper functions to adjust the document ranking.
=> Documentation and document ranking corrective functions

doc/_static/tf_idf_weighting.svg, doc/python/api.rst, freediscovery/feature_weighting.py, freediscovery/search.py, freediscovery/server/resources.py, freediscovery/server/schemas.py, freediscovery/server/tests/test_ingestion.py, freediscovery/tests/test_feature_weighting.py, freediscovery/tests/test_search.py, freediscovery/tests/test_text.py, freediscovery/text.py
Refactoring and documentation of tf-idf weighting schemes
=> Refactoring and documentation of tf-idf weighting schemes

appveyor.yml, build_tools/requirements_compat.txt, freediscovery/tests/test_feature_weighting.py
A PR aiming to fix CI on master
=> Fixing the CI on master

freediscovery/data/ds_003/example.csv, freediscovery/engine/tests/test_vectorizer.py, freediscovery/engine/vectorizer.py, freediscovery/server/resources.py, freediscovery/server/schemas.py, freediscovery/server/tests/test_categorization.py, freediscovery/server/tests/test_ingestion.py, requirements_engine.txt
This aims to add ingestion of CSV files.
If `column_ids` is provided the input file is assumed to be a CSV.
Work in progress.
=> Support ingestion of CSV files
