FreeDiscovery/FreeDiscovery

freediscovery/api/resources.py, freediscovery/clustering/base.py, freediscovery/tests/test_clustering.py
This PR adds a wrapper for DBSCAN clustering.
This algorithm can also be used to benchmark duplicate detection (i.e. mark as duplicates documents based on some cosine distance threshold).
**Edit:** note that the `eps` parameter in DBSCAN corresponds to `2*cosine_distance`, when features are L2 normalized.
=> Adding a wraper for DBSCAN clustering

.travis.yml, appveyor.yml, build_tools/circle/build_doc.sh, build_tools/requirements_conda.txt, build_tools/requirements_extra_pip.txt, circle.yml, conda_run.sh, doc/Makefile, docker_run.sh, examples/categorization_example.py, examples/clustering_example.py, examples/clustering_example_python.py, examples/duplicate_detection_example.py, freediscovery/api/app.py, freediscovery/api/resources.py, freediscovery/api/schemas.py, freediscovery/api/utils.py, freediscovery/datasets.py, freediscovery/tests/test_categorize.py, freediscovery/tests/test_datasets.py
This PR adds a mechanism for loading benchmark datasets (issue #9). Previously example had to include a number of helper functions, and relative paths to account for the difference in the environment, with this PR all the required operations are done internally with a call,
GET /api/v0/datasets/<dataset-name>
where `<dataset-name>` is one of,
- treclegal09_2k_subset  :   2 400 documents,   2 MB
- treclegal09_20k_subset :  20 000 documents,  30 MB
- treclegal09_37k_subset :  37 000 documents,  55 MB
- treclegal09            : 700 000 documents, 1.2 GB 
This allows to,
- simplify the examples files by removing all helper  functions relative to path transformations and OS compatibillity https://freediscovery.github.io/doc/dev/examples/index.html
- use the same examples file for the Docker …
=> Mechanism for downloading and loading benchmark datasets

doc/python_api.rst, doc/rest_api/categorization_post.md, doc/rest_api/feature_extraction_index_get.md, doc/rest_api/index.rst, doc/rest_api/lsi_predict_post.md, examples/categorization_example.py, freediscovery/categorization.py, freediscovery/datasets.py, freediscovery/lsi.py, freediscovery/server/app.py, freediscovery/server/resources.py, freediscovery/server/schemas.py, freediscovery/tests/run_suite.py, freediscovery/tests/test_categorize.py, freediscovery/tests/test_lsi.py, freediscovery/tests/test_server.py, freediscovery/tests/test_text.py, freediscovery/text.py, freediscovery/utils.py
This Pull Request addresses issue #4 and updates categorization and LSI modules to use numeric indexing instead of indexing by filenames,
- adds a `GET /api/v0/feature-extraction/<dataset-id>/index` endpoint that returns a list of document ids given a list of file-names.
- previously categorization and LSI accepted as input a list of relevant & non relevant file-names, which required to apply twice any operation on these lists. With this update, these methods take as input
- a list of document ids (`index`)
- target binary class relative to index (0 for non relevant or 1 for relevant)  (`y`)
this result in a more consistent API with respect to other ML libraries, have a more direct correspondence to ground truth files, and simplify categorization / LSI modules  and examples. Also related …
=> FIX Numeric indexing of the documents in categorization and LSI

freediscovery/categorization.py, freediscovery/cluster/base.py, freediscovery/tests/test_integration.py, freediscovery/tests/test_server.py
This adds additional integration tests to constrain the behavior of different models when they are used with and without the hashed feature extraction (issue #11 ).
=> Integration tests for models with and without hashed features

freediscovery/base.py, freediscovery/tests/test_text.py, freediscovery/text.py
This PR adds a private `_FeatureVectorizerSampled` class, on top of  [`FeatureVectorizer`](https://github.com/rth/FreeDiscovery/blob/d38fff87bf621489fa8f6ea3b1d33acba8db062d/freediscovery/text.py#L55) that can be used to downsample  / upsample the extracted features. Mostly useful for internal testing and experimenting in the context of binary classification.
=> Downsampling  / upsampling of the extracted features

freediscovery/io.py, freediscovery/tests/test_io.py
This PR adds a parser for the SMART stemmed format, used in particular for the RCV1-v2 dataset.
=> Adding a parser for RCV1 SMART stemmed format

.travis.yml, doc/rest_api/lsi_predict_post.md, examples/categorization_example.py, freediscovery/base.py, freediscovery/categorization.py, freediscovery/lsi.py, freediscovery/server/resources.py, freediscovery/server/schemas.py, freediscovery/tests/test_categorize.py, freediscovery/tests/test_integration.py, freediscovery/tests/test_lsi.py, freediscovery/tests/test_server.py, freediscovery/tests/test_text.py, freediscovery/text.py
This is a significant refactoring of nearest-neighbor categorization with LSI, including
- exposing a separate (and self consistent)  `freediscovery.categorization.NearestNeighborRanker` Python  class, following issue #48 
- replacing the previously used custom `NearestCentroidClassifier`  by the standard version from scikit-learn
- the `NearestNeighborRanker` can accept two types of input,
* negative and positive labels in the training set => classical nearest-neighbor-1 classifier (supervised)
* only positive labels => ranking based on the cosine distance (unsupervised)
- also addressing issue #15
**Update:** also dropping support for scikit-learn 0.17 in this PR due to maintenance costs.
=> Refactoring nearest-neighbor categorization with LSI

doc/check_links_in_docs.py
A script that crawls the documentation pages and checks that there are no broken links (e.g. links that return an HTTP 404 Error). 
This script named  `check_links_in_docs.py` and is located in the `doc/` folder.  The script can be executed as,
```
source activate freediscovery-env
python doc/check_links_in_docs.py BASE_URL
```
where BASE_URL could be for instance https://freediscovery.github.io/doc/0.7/, and print a list of URL with broken links together with the URL of the page where it happened
=> Detection of broken links in the docs

freediscovery/categorization.py, freediscovery/tests/test_categorize.py
scikit-learn has a `NearestCentroid` classification method (also known as  Rocchio classifier) however it cannot be used for ranking as the distance to the nearest centroid is not returned.
This PR subclasses this method in `freediscovery.categorization.NearestCentroidRanker` which can be used for categorization in the LSI space. This method was made standalone as part of the LSI refactoring step in PR #50 .
=> Add a NearestCentroid classification method

freediscovery/categorization.py, freediscovery/tests/test_categorize.py
This fixes issue #59 , and re-introduces a chunking mechanism for nearest neighbor search calculations (to keep a controlled RAM usage) . 
It appears that brute force nearest neighbor search outperforms the currently used `ball_tree` and besides does not produce exactly the same results (which could explain recent differences in LSI + NN1 categorization benchmarks).
=> FIX Use brute force nearest neighbor search by default 

examples/REST_categorization.py, examples/python_categorization.py, freediscovery/categorization.py, freediscovery/ingestion.py, freediscovery/parsers.py, freediscovery/search.py, freediscovery/server/resources.py, freediscovery/server/schemas.py, freediscovery/tests/test_categorize.py, freediscovery/tests/test_ingestion.py, freediscovery/tests/test_integration.py, freediscovery/tests/test_search.py, freediscovery/tests/test_server.py, freediscovery/tests/test_text.py, freediscovery/text.py
Currently FreeDiscovery can ingest documents in a folder specified  by `data_dir` parameter in the  `feature-extraction/` endpoint, then a unique `internal_id` is associated to each document, and all estimators estimators (e.g. categorization, clustering etc) take as input data specified by `internal_id` and return results as a function of `document_id`. 
This PR (work in progress) aims to add the ability to ingest documents specified by a list of dictionaries containing the file path of each file as well as the external `document_id` of each document (along with an optional `rendition_id`). The results of e.g. categorization could then also be returned, with the `original_id` (and `rendition_id`) specified.
This implementation thus adds a mapping layer between the `internal_id` used by …
=> [WIP] Use original document_id the REST API for data ingestion and results

freediscovery/cluster/base.py, freediscovery/text.py, freediscovery/utils.py
This PR includes a small refactoring of the `query_features` that allows to return the features used in a given document, and ensures that when returning top words characterizing a cluster, English stop words are removed.
=> Make sure that query_features uses english stop words

freediscovery/categorization.py, freediscovery/tests/test_categorize.py
This PR addresses the first step of issue #33 on computing the feature weights in the case of LogisticRegression in order the explain the categorization results.  The second step of the parent issue is being addressed by @DenisFLASH in PR #74 .
=> FIX Explain categorization results with LogisticRegression

build_tools/requirements_pip.txt, doc/rest_api/index.rst, freediscovery/server/app.py, freediscovery/server/resources.py, freediscovery/tests/test_server.py
This PR,
* removes the `flask_restfull` dependency (issue #7 )
* allows to generate an automatic REST API documentation (step 1 of issue #79  ) except for all endpoints except two (categorization and threading POST)
* as a side effect this appears to fix issue  https://github.com/FreeDiscovery/FreeDiscovery/issues/31 on exception handling though this would need additional verification.
@dmytrobondarchuk would you be able to review this PR?
=> REST API improvements

doc/whats_new.md, examples/REST_categorization.py, freediscovery/categorization.py, freediscovery/metrics.py, freediscovery/neighbors.py, freediscovery/server/app.py, freediscovery/server/resources.py, freediscovery/server/schemas.py, freediscovery/tests/test_categorize.py, freediscovery/tests/test_integration.py, freediscovery/tests/test_metrics.py, freediscovery/tests/test_neighbors.py, freediscovery/tests/test_server.py, freediscovery/tests/test_utils.py, freediscovery/utils.py
This PR allows to perform multi-class categorization with FreeDiscovery (issue #87) and changes the REST API accordingly. It also allows to set a limit on the number of returned categories (issue #88 ).
=> Multiclass categorization

freediscovery/stop_words.py, freediscovery/tests/test_stop_words.py
According to issue #64 (Mechanism for adding custom stop words):
- added a _StopWordsWrapper class to freediscovery/stop_words.py
- added corresponding tests to freediscovery/tests/test_stop_words.py 
If this PR looks OK, REST API endpoints will be implemented with next PR.
=> Mechanism for adding and managing custom stop words

examples/REST_categorization.py, freediscovery/server/schemas.py, freediscovery/server/tests/test_clustering.py, freediscovery/server/tests/test_duplicate_detection.py
Since GET endpoints cannot accept parameters in the payload, this PR ensures that the corresponding parameters are passed in the URL string.
=> Encode GET request parameters in the URL string

README.rst, doc/whats_new.md, examples/REST_categorization.py, examples/REST_semantic_search.py, freediscovery/categorization.py, freediscovery/datasets.py, freediscovery/ingestion.py, freediscovery/server/app.py, freediscovery/server/resources.py, freediscovery/server/schemas.py, freediscovery/server/tests/base.py, freediscovery/server/tests/test_categorization.py, freediscovery/server/tests/test_ingestion.py, freediscovery/server/tests/test_metrics.py, freediscovery/server/tests/test_search.py, freediscovery/tests/test_categorize.py, freediscovery/tests/test_integration.py, freediscovery/utils.py
This PR adapts the categorization metrics to handle more than 2 classes. It also,
- removes the `internal_id` field from categorization and semantic search.
- makes the `20newsgoup` dataset use a smaller training set in tests
=> Adapted metrics to multiclass categorization 

doc/Makefile, doc/python_api.rst, doc/whats_new.md, examples/REST_clustering.py, examples/REST_duplicate_detection.py, freediscovery/categorization.py, freediscovery/cluster/base.py, freediscovery/dupdet/base.py, freediscovery/metrics.py, freediscovery/server/app.py, freediscovery/server/resources.py, freediscovery/server/schemas.py, freediscovery/server/tests/test_clustering.py, freediscovery/server/tests/test_duplicate_detection.py, freediscovery/tests/test_metrics.py
This PR refactors the clustering and duplicate detection API in order to remove the need for manual document id mapping as was previously done for categorization and semantic search. This also affects PR #75 .
=> Refactoring of the clustering / dup. detection API

freediscovery/server/resources.py, freediscovery/server/tests/test_custom_stop_words.py, freediscovery/stop_words.py, freediscovery/tests/test_stop_words.py
added a `DELETE /stop-words/<name>` endpoint with corresponding unittests and schema definition.
=> DELETE custom stop words endpoint

freediscovery/tests/run_suite.py
I change the temp directory to the python default one. This would make the repository cleaner when running on windows environment. 
This would also work on linux since the default temp file directory is also /tmp/
=> change temp dir to python default

freediscovery/server/tests/base.py, freediscovery/server/tests/test_categorization.py, freediscovery/server/tests/test_clustering.py, freediscovery/server/tests/test_custom_stop_words.py, freediscovery/server/tests/test_duplicate_detection.py, freediscovery/server/tests/test_email_threading.py, freediscovery/server/tests/test_ingestion.py, freediscovery/server/tests/test_lsi.py, freediscovery/server/tests/test_metrics.py, freediscovery/server/tests/test_search.py, freediscovery/server/tests/test_various.py
This PR adds the `post_check`, `get_check`, `delete_check` methods to the flask test client, that,
-  check that the call succeded (e.g. return code 200)
- converts the json response to a python dict
which allows to reduce code repetitions in all the tests suite (and remove the calls to `parse_res` function).
=> MNT Improve REST unit tests

Makefile, freediscovery/search.py, freediscovery/server/resources.py, freediscovery/server/tests/test_search.py
This PR adds the `query_document_id` parameter to the semantic search which allows to pass a document id as search query instead of a user provided text.
=> Added the query_document_id parameter to semantic search

Dockerfile, examples/python_categorization.txt, examples/python_clustering.py_disabled, freediscovery/externals/flask_compress.py, freediscovery/externals/joblib_pool.py, freediscovery/server/app.py, freediscovery/server/tests/base.py, freediscovery/tests/run_suite.py, freediscovery/tests/test_base.py
This PR,
* adds automatic gzip compression to REST API responses when the builtin flask Werkzeug server is used (which has a significant performance impact)
* automatically removes the created `cache_dir` after unit tests are executed.
=> MNT remove cache_dir at the end of unit tests

freediscovery/categorization.py, freediscovery/server/resources.py, freediscovery/server/tests/test_categorization.py, freediscovery/server/tests/test_search.py, freediscovery/server/validators.py, freediscovery/tests/test_categorize.py
This PR replaces the `sort=bool` parameter in semantic search and categorization by,
- `sort_by` in ['scores', None]
- `sort_order` in ['ascending', 'descending']
it also ensures that `max_results <= 0` returns all the results.
=> Additional sorting options

doc/user_manual/scaling_benchmarks.rst, freediscovery/ingestion.py, freediscovery/search.py, freediscovery/server/resources.py, freediscovery/server/schemas.py, freediscovery/server/tests/test_search.py, freediscovery/text.py
This PR optimises semantic search and adds a pagination ability. Previously search in a 700k document collection took 180 s; this update decreases this number to,
- 50 s if the scores of all document are returned
- 15 s if only the first page of results is returned
=> Performance optimization and pagination in search

freediscovery/categorization.py, freediscovery/datasets.py, freediscovery/pipeline.py, freediscovery/search.py, freediscovery/server/resources.py, freediscovery/server/tests/base.py, freediscovery/server/tests/test_categorization.py, freediscovery/server/tests/test_clustering.py, freediscovery/server/tests/test_email_threading.py, freediscovery/server/tests/test_exceptions.py, freediscovery/server/tests/test_ingestion.py, freediscovery/server/tests/test_lsi.py, freediscovery/server/tests/test_search.py, freediscovery/tests/run_suite.py, freediscovery/tests/test_categorize.py, freediscovery/tests/test_text.py
This PR,
- enforces that computing nearest neighbors on documents without applying an LSI preprocessing step would raise an error (except in the case when the query is user provided and contains only key words) (issue #126 )
- renames `nn_metric` parameter to `metric`
- adds additional tests to semantic search / categorization
- removes no longer necessary `from __future__` imports.
=> Additional tests for semantic search / categorization

examples/REST_clustering.py, freediscovery/cluster/base.py, freediscovery/server/resources.py
This fixes issue #133 , with occasional  recursion  errors when saving birch clustering objects to disk.  The  transverse  linkage (via `prev_leaf_` and `next_leaf_` attributes of _CFNode`) is removed in the hierarchical tree  since it  is not used in FreeDiscovery anyway and it made the resulting structure harder to pickle .
=> FIX hierarchical clustering recursion limit

circle.yml, freediscovery/__main__.py, freediscovery/server/app.py, freediscovery/server/info.py, freediscovery/server/tests/test_various.py
This adds a root endpoint with server information. Running `curl -X GET http://localhost:5001/` would produce something similar to,
```
{
"config": {
"cache_dir": "/home/user/freediscovery_shared", 
"debug": false, 
"hostname": "0.0.0.0", 
"log_file": "/home/user/freediscovery_shared/freediscovery-backend.log", 
"n_workers": 6, 
"port": 5001, 
"server": "werkzeug"
}, 
"env": {
"python_version": "3.6.1 |Continuum Analytics, Inc.| (default, May 11 2017, 13:09:58) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]"
}, 
"version": {
"number": "1.1.0"
}
}
```
=> Added URL endpoint with server info

.codecov.yml, .coveragerc, freediscovery/ingestion.py, freediscovery/server/resources.py, freediscovery/server/tests/test_ingestion.py, freediscovery/tests/test_ingestion.py, freediscovery/text.py
This PR adds an optional parameter `document_id_generator` for the
`POST /api/v0/feature-extraction/{dataset_id}'` endpoint. When set to `infer_file_path` the system will attempt to generate a meaningful numeric `document_id` from the document file name. 
This is mostly used to make examples more comprehensible.
=> Generating `document_id` from document filenames 

README.rst, freediscovery/server/resources.py, freediscovery/server/schemas.py, freediscovery/server/tests/test_ingestion.py, freediscovery/server/tests/test_search.py
Previously, by default,  stop words were not used. 
With this PR english stop words are used by default. This should improve the significance of the computed similarity scores with default parameters, reduce TF matrix sizes (and the corresponding computational time). For other languages than English, a custom list can be specified, and even the English list shouldn't hurt.
=> Use english stop words by default

README.rst, build_tools/requirements_compat.txt, freediscovery/externals/sklearn_backport/README.md, freediscovery/externals/sklearn_backport/metrics/__init__.py, freediscovery/externals/sklearn_backport/metrics/base.py, freediscovery/externals/sklearn_backport/metrics/ranking.py, freediscovery/metrics.py, freediscovery/server/resources.py, requirements.txt
This PR backports a  few ranking metrics  (under `freediscovery.externals.sklearn_backport`) from the not yet release scikit-learn v0.19. In particular, v0.19  adds a few enhancements and bug fixes for the `mean_average_precision`  and `roc_auc` calculations (cf [release notes](https://github.com/scikit-learn/scikit-learn/blob/56a21ea6919867fba5b2d6686014d6b98b7dae94/doc/whats_new.rst)), and also adds the Discounted cumulative gain (DCG) score that can be used to benchmark semantic search.
=> Backport ranking metrics from sklearn 0.19

benchmarks/ingestion.py, freediscovery/categorization.py, freediscovery/ingestion.py, freediscovery/io.py, freediscovery/lsi.py, freediscovery/preprocessing.py, freediscovery/server/app.py, freediscovery/server/resources.py, freediscovery/server/schemas.py, freediscovery/server/tests/test_ingestion.py, freediscovery/server/tests/test_preprocessing.py, freediscovery/server/tests/test_search.py, freediscovery/tests/test_io.py, freediscovery/text.py
This PR adds a mechanism to allow optional pre-processing of documents before vectorizations, via the `preprocess` argument of the `POST /feature-extraction'` endpoint. Included filiters are,
- ''emails_ignore_headers": allowing to ignore most frequent header fields when processing emails
This  PR  fixes the random_seed for all processing steps that take random state as input, in order to ensure reproducibility. The random seed can be modified with the `FREEDISCOVERY_RANDOM_SEED` environment variable. 
This also improves the parser for the SMART tokenization file format.
=> Mechanism for preprocessing steps

circle.yml, freediscovery/datasets.py, freediscovery/engine/tests/test_ingestion.py, freediscovery/feature_weighting.py, requirements_engine.txt
Marshmallow 3 introduces [breaking changes](http://marshmallow.readthedocs.io/en/latest/upgrading.html#upgrading-to-3-0) and [is still in beta](https://pypi.org/project/marshmallow/#history). This PR ensures that the installed version of marshmallow is 2.x. Also adds some PEP8 improvements.
=> MAINT Use Marshmallow 2.x
